name: 'Production Build'
 
on:
  push:
    branches: ['main']
 
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
 
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Use Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: 'x64'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci --skip-scripts
        working-directory: data-processor
      - run: npm run job
        working-directory: data-processor
 
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website
          commit_message: "Production deploy -- ${{ github.event.head_commit.message }}"
